general.import = ["~/.config/alacritty/themes/rose-pine.toml"]

[terminal.shell]
program = "tmux"

[window]
startup_mode = "Maximized"
decorations = "None"
padding = { x = 5, y = 10 }
dynamic_padding = true
opacity = 0.85
blur = true

[font]
size = 12

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "Italic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[cursor]
style = {shape = "Block", blinking = "Off"}
