import = ["~/.config/alacritty/themes/rose-pine.toml"]

[shell]
program = "tmux"

[window]
startup_mode = "Maximized"
decorations = "None"
padding = { x = 2, y = 2 }
dynamic_padding = true
#opacity = 0.8
#blur = true

[font]
size = 11

[font.bold]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaCove Nerd Font Mono"
style = "Italic"

[font.normal]
family = "CaskaydiaCove Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[cursor]
style = {shape = "Block", blinking = "Off"}
